In [1]:
!pip install pandas mysql-connector-python

Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: mysql-connector-python in /opt/conda/lib/python3.11/site-packages (9.3.0)
Requirement already satisfied: numpy>=1.23.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [4]:
# Read data from a source: Extract
import pandas as pd

# Simulated raw data

data = {
    "id": [1,2,3],
    "name": ["abc", "jkl", "uvw"],
    "age": [25, 30, 35]
}

df = pd.DataFrame(data)
df

   id name  age
0   1  abc   25
1   2  jkl   30
2   3  uvw   35

In [5]:
# Transform: Clean/Modify the data
# Example: add a new column
df["age_category"] = df["age"].apply(lambda x : "Young" if x < 30 else "Adult")
df

   id name  age age_category
0   1  abc   25        Young
1   2  jkl   30        Adult
2   3  uvw   35        Adult

In [6]:
import mysql.connector

conn = mysql.connector.connect(
    host = "mysql_container1",
    user = "projectuser",
    password = "projectpass",
    database = "projectdb"
)

cursor = conn.cursor()

cursor.execute("""CREATE TABLE IF NOT EXISTS users (
id INT PRIMARY KEY,
name VARCHAR(100),
age INT,
age_category VARCHAR(30)
);""")

# Insert data row by row
for _, row in df.iterrows():
    cursor.execute("REPLACE INTO users (id, name, age, age_category) VALUES (%s, %s, %s, %s)", (row['id'], row['name'], row['age'], row['age_category']))

conn.commit()
cursor.close()
conn.close()
print("Data loaded into MySQL.")

Data loaded into MySQL.